### ISSUE TITLE
Auth or sale with CIM not working 

### ISSUE THREAD

**Issue by waskel** [vcatalano/py-authorize#59]
I'm trying to use CIM for auth/sale and getting the following errors:
Traceback (most recent call last):
  File "cc-cust-testCIM.py", line 15, in <module>
    'payment_id': '1500217971',
  File "build/bdist.linux-x86_64/egg/authorize/transaction.py", line 12, in auth
  File "build/bdist.linux-x86_64/egg/authorize/apis/transaction_api.py", line 29
, in auth
  File "build/bdist.linux-x86_64/egg/authorize/apis/authorize_api.py", line 68,
in _make_call
authorize.exceptions.AuthorizeResponseError: E00027: Card Code is required.

I'm sending 'customer_id' and 'payment_id'. No matter what the last param is, it shows up as the error line. I've triple-checked the syntax, everything appears exactly as you example (with different values). 
result = authorize.Transaction.sale({
    'amount': 56.00,
    'customer_id': '19086684',
    'payment_id': '17633614',
})

Any ideas would be helpful. Though I have yet to receive a response to my other issue, I still have hope.
Thanks!

**Comment by vcatalano** [comment]
After emailing back and forth with @waskel, it appears that this is not an issue on the production environment. I'm going to go ahead and close this issue.
